version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    restart: always
#    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://gitlab.example.com'
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "22:22"     # SSH
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab_network

volumes:
  gitlab_config:
    driver: local
  gitlab_logs:
    driver: local
  gitlab_data:
    driver: local

networks:
  gitlab_network:
    driver: bridge
